apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: risk-assessment-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/covid-net-service/risk-assessment:latest