apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: risk-assessment
spec:
  consumerGroup: risk-assessment
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  topics: covid-notification
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: risk-assessment
